// DB row -> frontend Property object
export function rowToProperty(row) {
  return {
    id: row.id,
    name: row.name,
    location: row.location,
    type: row.type,
    bedrooms: row.bedrooms,
    unitTypes: row.unit_types,
    area: row.area,
    price: row.price,
    priceAED: row.price_aed,
    rentalYield: row.rental_yield === null ? null : Number(row.rental_yield),
    appreciation: row.appreciation === null ? null : Number(row.appreciation),
    developer: row.developer,
    completion: row.completion,
    tag: row.tag,
    tagCol: row.tag_col,
    tier: row.tier,
    standout: row.standout,
    description: row.description,
    image: row.image,
    gallery: row.gallery || [],
    zone: row.zone,
    views: row.views,
    floors: row.floors,
    totalUnits: row.total_units,
    availableUnits: row.available_units,
    status: row.status,
    minDeposit: row.min_deposit,
    handoverQuarter: row.handover_quarter,
    amenities: row.amenities || [],
    paymentPlan: row.payment_plan || [],
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  }
}

// Frontend Property payload -> DB column values (used for INSERT/UPDATE)
export function propertyToRow(p) {
  return {
    name: p.name ?? '',
    location: p.location ?? '',
    type: p.type ?? '',
    bedrooms: p.bedrooms ?? 0,
    unit_types: p.unitTypes ?? '',
    area: p.area ?? '',
    price: p.price ?? '',
    price_aed: p.priceAED ?? '',
    rental_yield: p.rentalYield ?? 0,
    appreciation: p.appreciation ?? 0,
    developer: p.developer ?? '',
    completion: p.completion ?? '',
    tag: p.tag ?? '',
    tag_col: p.tagCol ?? '#C9A44A',
    tier: p.tier ?? 'Mid-Range',
    standout: p.standout ?? '',
    description: p.description ?? '',
    image: p.image ?? '',
    gallery: JSON.stringify(p.gallery ?? []),
    zone: p.zone ?? '',
    views: p.views ?? 0,
    floors: p.floors ?? 0,
    total_units: p.totalUnits ?? 0,
    available_units: p.availableUnits ?? p.totalUnits ?? 0,
    status: p.status === 'unavailable' ? 'unavailable' : 'available',
    min_deposit: p.minDeposit ?? '',
    handover_quarter: p.handoverQuarter ?? '',
    amenities: JSON.stringify(p.amenities ?? []),
    payment_plan: JSON.stringify(p.paymentPlan ?? []),
  }
}
